# Generated by Django 2.2 on 2020-04-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=40)),
                ('task_status', models.CharField(choices=[('CR', 'CREATED'), ('CP', 'COMPLETED')], max_length=20)),
            ],
        ),
    ]
