# Generated by Django 2.2 on 2020-04-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_items',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
